[package]
name = "kaijutsu-client"
version.workspace = true
edition.workspace = true
description = "Cap'n Proto RPC client library for kaijutsu"

[features]
default = []
telemetry = ["kaijutsu-telemetry/telemetry"]

[dependencies]
capnp.workspace = true
capnp-rpc.workspace = true
tokio.workspace = true
tokio-util.workspace = true
futures.workspace = true
russh.workspace = true
rand.workspace = true
log.workspace = true
thiserror.workspace = true
whoami.workspace = true
serde_json = "1"
tracing = "0.1"
kaijutsu-telemetry = { workspace = true }

# Shared CRDT types
kaijutsu-crdt = { path = "../kaijutsu-crdt" }

[build-dependencies]
capnpc.workspace = true

[dev-dependencies]
env_logger.workspace = true
